project/main/VigorWeb/VigorWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site1.urls')),
]

project/main/VigorWeb/site1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .models import *
from django.views.generic import ListView
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from .views import ImageUploadView

urlpatterns = [
#     path('',views.home,name='home'),
#     path('introduction/',views.introduction,name='introduction'),
#     path('heallthinfo/',views.heallthinfo,name='heallthinfo'),
#     path('loseweight/',views.loseweight,name='loseweight'),
#     path('tools/',views.tools,name='tools'),
#     path('login/',views.loginPage,name='login'),
#     path('logout/',views.logoutPage,name='logout'),
#     path('register/',views.register,name='register'),
#     path('verify/',views.verifyOTP,name='verify'),
#     path('social-auth/', include('social_django.urls', namespace='social')),
# ]
    path('', views.home, name='home'),
    path('introduction/', views.introduction, name='introduction'),
    # path('blog/',views.heallthinfo,name='blog'),
    path('loseweight/', views.loseweight, name='loseweight'),
    path('autosuggest/', autosuggest, name='autosuggest'),
    path('search/', views.search, name='search'),
    path('calo/', views.calo, name='calo'),
    path('tools/', views.tools, name='tools'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('register/', views.register, name='register'),
    path('verify/', views.verifyOTP, name='verify'),
    path('ver/', views.verify, name='ver'),
    path('account/', views.account, name='account'),
    path('forgot-password/', views.forgotpass, name='forgot'),
    path('change-password/', views.changepass, name='changepass'),
    
    path('blog/', ListView.as_view(
        queryset=Post.objects.all().order_by('-date'),
        template_name='site1/blog.html',
        context_object_name='Posts',
        paginate_by=10), name='blog'),
    path('<int:pk>-<str:title>/', views.post, name='post'),
    path('reply/<int:pk>-<str:title>/', views.reply_cmt, name='reply'),
    path('blog/write_blog/', views.write_blog, name='write_blog'),
    
    path('fruits/', views.ListFruit, name='list-fruits'),
    path('fruits/<str:classification>/', FruitListView.as_view(), name='fruits'),
    path('fruits/<str:classification>/<str:name>',views.FruitsPage, name='fruitspage'),
    
    path('foods/', views.ListFoods, name='list-foods'),
    path('foods/<str:classification>/', FoodListView.as_view(), name='foods'),
    path('foods/<str:classification>/<str:name>', views.FoodsPage, name='foodspage'),
    
    path('news/<str:type>/', views.News, name='news'), 
    path('news/', views.ListNews, name='list-news'), 
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('upload/', ImageUploadView.as_view(), name='upload'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/main/VigorWeb/site1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from datetime import datetime
# Create your models here.


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post_image = models.ForeignKey(
        'Image', on_delete=models.SET_NULL, null=True, related_name='post_images')

    def __str__(self):
        return self.title

    @property
    def ImageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(null=True, upload_to='post_images/')
    title = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f"Image for {self.post.date} - {self.post.title}"

class MemberImage(models.Model):
    title = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, upload_to='member_images/')
    def __str__(self):
        return f"Image of {self.title}"


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.post}'


class Reply(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='replies')
    body = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Replied by {self.author} for {self.comment}'


class Fruit(models.Model):
    CLASSIFICATION_CHOICES = [
        ('high_calories', 'Nhiều Calo'),
        ('low_calories', 'Ít Calo'),
        ('medium_calories', 'Calo Vừa Phải'),
    ]
    name = models.CharField(max_length=100)  # Tên của trái cây
    description = models.TextField()         # Mô tả trái cây
    calories = models.IntegerField()         # Lượng calo của trái cây
    classification = models.CharField(
        max_length=50, choices=CLASSIFICATION_CHOICES)  # Phân loại trái cây
    # Hình ảnh của trái cây
    image = models.ImageField(upload_to='fruit_images/')

    def __str__(self):
        return self.name


class Food(models.Model):
    CLASSIFICATION_CHOICES = [
        ('high_calories', 'Nhiều Calo'),
        ('low_calories', 'Ít Calo'),
        ('medium_calories', 'Calo Vừa Phải'),
    ]
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500, null=True, blank=True)
    calories = models.IntegerField()
    unit = models.CharField(max_length=50, null=True)
    classification = models.CharField(
        max_length=50, choices=CLASSIFICATION_CHOICES)
    # Hình ảnh của trái cây
    image = models.ImageField(upload_to='foods_images/')

    def __str__(self):
        return self.name


class NewsItem(models.Model):
    title = models.CharField(max_length=255)
    pub_date = models.DateTimeField()
    # Ensure unique links to avoid duplicates
    link = models.URLField(unique=True)
    description_text = models.TextField()
    image = models.URLField()
    type = models.CharField(max_length=50, null=True)  # Thêm trường type

    def __str__(self):
        return self.title

project/main/VigorWeb/site1/forms.py
from django import forms
from .models import *
import re
from django.contrib.auth.models import User

class CommentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author', None)
        self.post = kwargs.pop('post', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        comment = super().save(commit=False)
        comment.author = self.author
        comment.post = self.post
        if commit:
            comment.save()
        return comment

    class Meta:
        model = Comment
        fields = ["body"]


class RelyCommentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author', None)
        self.comment = kwargs.pop('comment', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        Reply = super().save(commit=False)
        Reply.author = self.author
        Reply.comment = self.comment
        Reply.save()

    class Meta:
        model = Reply
        fields = ["body"]


class ImageUploadForm(forms.Form):
    images = forms.ImageField(required=False)
    title = forms.CharField(label="", required=False,
                           widget=forms.TextInput
                           (attrs={
                               'class': 'blog_img',
                               'name': 'blogimg',
                               'placeholder': 'Tiêu đề ảnh',
                               'required': 'True'
                            }))
    
    fields = ['title']


class BlogForm(forms.ModelForm):
    title = forms.CharField(label="", required=False,
                           widget= forms.TextInput
                           (attrs={
                               'class': 'blog_title',
                               'name': 'blogtitle',
                               'placeholder':'Tiêu đề...',
                               'required': 'True'
                            }))
    body = forms.CharField(label="", required=False,
                           widget= forms.Textarea
                           (attrs={
                               'class': 'blog_body',
                               'name': 'blogbody',
                               'placeholder':'Nội dung...',
                               'required': 'True'
                            }))


    class Meta:
        model = Post
        fields = ['title', 'body']

    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        post = super().save(commit=False)
        post.author = self.author

        if commit:
            post.save()  

            # Lưu các hình ảnh được cung cấp
            if self.cleaned_data.get('images'):
                images = self.cleaned_data['images']# Lấy giá trị của title từ trường ẩn image_title
                for image in images:
                    Image.objects.create(image=image, post=post)

        return post

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Tài khoản', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Mật khẩu', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Nhập lại mật khẩu', widget=forms.PasswordInput())

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
        raise forms.ValidationError("Mật khẩu không hợp lệ")

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^[\w]+$', username):
            raise forms.ValidationError("Tên tài khoản có kí tự đặc biệt")
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError("Tài khoản đã tồn tại")
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email đã tồn tại")
        return email
    def save(self):
        User.objects.create_user(username=self.cleaned_data['username'], email=self.cleaned_data['email'], password=self.cleaned_data['password1'])

project/main/VigorWeb/site1/templates/site1/account.html
{% extends 'site1/base.html' %}
{%load static%}
{% block account %}

<!-- pip install requests -->
<head>
<title>Trang Cá Nhân</title>
</head>
<section class="slider-area">
    <div class="slider-area-photo"></div>
    <div class="container">
        <div class="slider-row">
            <div class="col-xl-6 col-lg-8 col-md-8">
                <div class="slider-row-caption">
                    <h1 style="font-size: 3.5rem;">Quản Lý Tài Khoản</h1>
                    <nav aria-label="slider-nav">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}" tabindex="0">Trang Chủ</a></li>
                            <li class="breadcrumb-item"><a href="" tabindex="0">Tài Khoản</a></li>
                            
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="about-us-section">
    <div class="about-container">
        <div class="about-us-section-row">
            <div class="about-us-section-tittle">
                <h2>Tài khoản của bạn</h2>
                <p class="about-p-long" style="width: 600px;">
                    Xin chào {{user.username}}! Đây là trang cá nhân của bạn. Bạn có thể xem thông tin cá nhân, 
                    thay đổi mật khẩu của mình. Chúc bạn vui vẻ!
                </p>
            </div>
        </div>
    </div>
</section>


<section class="calo-empty-space"></section>

<div class="container mt-3 mb-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Thông Tin Tài Khoản</h3>
                    
                        <div class="mb-3 input-group">
                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                            <input type="text" class="form-control" placeholder="Tên Tài Khoản" value="{{ user.username }}" readonly>
                        </div>
                        <div class="mb-3 input-group">
                            <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                            <input type="email" class="form-control" placeholder="Email" value="{{ user.email }}" readonly>
                        </div>
                        <div class="mb-3 input-group">
                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                            <input type="text" class="form-control" placeholder="Tên" value="{{ user.first_name }}" readonly>
                        </div>
                        <div class="mb-3 input-group">
                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                            <input type="text" class="form-control" placeholder="Họ" value="{{ user.last_name }}" readonly>
                        </div>
                        
                        {% load auth_backends %}
                        <div class="text-right mt-3">
                            {% if not user|is_google_backend %}
                            <a href="{% url 'changepass' %}" class="btn btn-primary">Đổi Mật Khẩu</a>
                            {% else %}
                            <a href="" class="btn btn-primary">Google User không thể đổi mật khẩu tại đây!</a>
                            {% endif %}
                        </div>
                        
                    
                </div>
            </div>
        </div>
    </div>
</div>






{% endblock account %}

project/main/VigorWeb/site1/templates/site1/blog.html
{% extends 'site1/base.html' %}
{% load static %}
{% block heallthinfo-content %}
<head>
    <title>Blog</title>
    <link href="{% static 'site1/css/blog.css' %}" rel="stylesheet">
    <link href="{% static 'site1/css/rpBlog.css' %}" rel="stylesheet">

</head>
<section class="slider-area">
    <div class="slider-area-photo"></div>
    <div class="container">
        <div class="slider-row">
            <div class="col-xl-6 col-lg-8 col-md-8">
                <div class="slider-row-caption">
                    <h1>Blog</h1>
                    <nav aria-label="slider-nav">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}" tabindex="0">Trang Chủ</a></li>
                            <li class="breadcrumb-item"><a href="#" tabindex="0">Blog</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>

{% for post in Posts %}
    {% if forloop.counter|divisibleby:2 %}

    <section class="about-us-section" style="background-color:#f4f4f4">
        <div class="about-container">
            <div class="about-us-section-row">
                <div class="about-us-section-tittle">
                    <h2><a href="{% url 'post' post.id post.title%}" style="color:black">{{ post.title }}</a></h2>
                    <p class="about-p-long" style="margin-bottom: 7rem;">{{ post.body|safe }}</p>
                </div>
            </div>
            
            <div class="about-picture-group-1">
            
                {% for img in post.image_set.all %}
                <div class="about-picture-2">
                    <img src="{{ img.image.url }}" alt="">
                    <p class="picture-title-2">{{ img.title }}</p>
                </div>
                {% endfor %}
            </div>
            <div class="ddt_tailor-details">
                <div class="ddt_btn">
                    <a href="{% url 'post' post.id post.title %}" class="border-btn">Xem Thêm</a>
                </div>
            </div>
            </div>
        </div>
    </section>
    {% else %}
    <section class="about-us-section">
        <div class="about-container">
            <div class="about-us-section-row">
                <div class="about-us-section-tittle">
                    <h2><a href="{% url 'post' post.id post.title%}" style="color:black">{{ post.title }}</a></h2>
                    <p class="about-p-long" style="margin-bottom: 7rem;">{{ post.body|safe }}</p>
                </div>
            </div>

            <div class="about-picture-group-1">
            
                {% for img in post.image_set.all %}
                <div class="about-picture-2">
                    <img src="{{ img.image.url }}" alt="">
                    <p class="picture-title-2">{{ img.title }}</p>
                </div>
                {% endfor %}
            </div>
            <div class="ddt_tailor-details">
                <div class="ddt_btn">
                    <a href="{% url 'post' post.id post.title %}" class="border-btn">Xem Thêm</a>
                </div>
            </div>
            </div>
        </div>
    </section>
    {% endif %}
{% endfor %}

{% endblock heallthinfo-content %} 

project/main/VigorWeb/site1/templates/site1/register.html
{% comment %} {% extends 'site1/base1.html' %} {% endcomment %}
{% load static %}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <meta charset="utf-8" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Đăng Ký</title>
    <link rel="stylesheet" href="{% static 'site1/font/themify-icons-font/themify-icons/themify-icons.css' %}" />
    <link href="{% static 'site1/css/base.css' %}" rel="stylesheet" />
    <link href="{% static 'site1/css/register.css' %}" rel="stylesheet" />
    <link href="{% static 'site1/css/main.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'site1/css/qlResIndex' %}" />
    <link rel="stylesheet" href="{% static 'site1/css/qlResIndex_body' %}" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />

    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="icon" type="image/x-icon" href="{% static 'site1\logo\vigor_logo_2.png' %}" sizes="32x32" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/assests/font/themify-icons-font/themify-icons/themify-icons.css" />

    <!-- js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="background">
      <img src="https://images.pexels.com/photos/2261483/pexels-photo-2261483.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="background" style="width:100%; height:100%; position: absolute;" />

      <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100" style="max-width:1000px">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Đăng ký</p>

                      <form class="mx-1 mx-md-4" method="POST" action="">
                        {% csrf_token %}
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example1c"></label>

                            <input style="border:solid 1px; width:250px" type="text" name="username" maxlength="150" autofocus="" required="" aria-describedby="id_username_helptext" id="id_username" placeholder="Tên Tài Khoản" />
                          </div>
                        </div>

                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example3c"></label>
                            <input style="border:solid 1px; width:250px" type="email" name="email" maxlength="254" id="id_email" placeholder="Email" />
                          </div>
                        </div>

                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example1c"></label>
                            <input style="border:solid 1px; width:250px" type="text" name="first_name" maxlength="150" id="id_first_name" placeholder="Tên" />
                          </div>
                        </div>

                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example1c"></label>
                            <input style="border:solid 1px; width:250px" type="text" name="last_name" maxlength="150" id="id_last_name" placeholder="Họ" />
                          </div>
                        </div>

                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example4c"></label>
                            <input style="border:solid 1px; width:250px" type="password" name="password1" autocomplete="new-password" required="" aria-describedby="id_password1_helptext" id="id_password1" placeholder="Mật Khẩu" />
                          </div>
                        </div>

                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example4cd"></label>
                            <input style="border:solid 1px; width:250px" type="password" name="password2" autocomplete="new-password" required="" aria-describedby="id_password2_helptext" id="id_password2" placeholder="Nhập lại Mật Khẩu" />
                          </div>
                        </div>

                        <div class="d-flex justify-content-center mx-4 mb-lg-4">
                          <button type="submit" class="btn btn-primary btn-lg">Đăng Ký</button>
                        </div>

                        {% comment %} <div class="row justify-content-center">
                          <button class="btn btn-primary mb-2" style="width:250px"><a href="{% url 'social:begin' 'google-oauth2' %}">Continue With Google</a></button>
                        </div> {% endcomment %}

                        <p class="text-center h5 fw-bold mb-5 mx-1 mx-md-4 mt-4">
                          Bạn đã có tài khoản? <a href="{% url 'login' %}">Đăng Nhập</a>
                        </p>
                      </form>
                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                      <img src="https://images.pexels.com/photos/128402/pexels-photo-128402.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" style="width:100%; height:90%; object-fit: cover; border-radius: 8px;" class="img-fluid" alt="image" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </body>
</html>